<?php
function greeting_menu() {
  $items = array();
  $items['hello_friend'] = array(
    'title'=> "Hello Friend!",
    'page callback' => 'say_hello',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  $items['goodbye'] = array(
    'title' => 'GoodBye Friend',
    'page callback' => 'say_goodbye',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}
function say_hello(){
  return '<p>Hello, Darkness, my old friend</p>';
}
function say_goodbye(){
  return '<p>Thanks for the memories</p>';
}

function greeting_user_login(){
  $_GET['destination'] = 'hello_friend';
}
function greeting_user_logout(){
  $_GET['destination'] = 'goodbye';
}
